services:
  louvorapp:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: louvorapp
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
